### ISSUE TITLE
can you please add this plugin to docker hub

### ISSUE THREAD

**Issue by lingenavd** [joshinryz/ansible_ldap_inventory#12]
Hello,

Great work on the plugin!
Can you please add this plugin to the docker hub?
That would be great, it would make it much easier to implement with the native Docker commands.

Thanx in advance!
grtz,
Andre

**Comment by joshinryz** [comment]
Hey Andre,

Im assuming you mean the ansible/ansible image. Unfortunately, I havent had plans to integrate this into the ansible community.windows collection - as the testing may be outside of the scope of the project. (getting an ldap / ad server to test against in a docker image). I'd be happy if someone wants to take the code and work on it, as I know Jordan is aware of the plugin.

Thanks for the feedback.

Josh

**Comment by lingenavd** [comment]
Hi Josh,

What I meant is to create a real plugin which is also a separate downloadable content item in docker hub.
If you open docker hub you can search for images but also for plugins.
The advantage of a plugin in docker hub is that the plugin could be downloaded and implemented with the docker native commands just like you would do for the images from docker hub.
Plugins are from what I understand separate content items next to images.
This is to be able to create separate plugins instead of the hassle to embed them in every image in which it would be helfull to have the plugin.
Or maybe I misunderstand the whole plugin section on docker hub.
Maybe you can have a look at it.

With regards,
Andre

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________
