### ISSUE TITLE
Is there a way to import the host using the dNSHostName attribute?

### ISSUE THREAD

**Issue by smaksimus** [joshinryz/ansible_ldap_inventory#13]
Unfortunately our hostnames don't line up with their AD/LDAP object labels 1:1 so I was wondering whether it might be possible to somehow import the hostname using the object's dNSHostName attribute instead? Thanks.

**Comment by joshinryz** [comment]
ok - i made a change to make the attribute the plugin uses for hostnames a variable. Feel free to change it from 

hostname_field = "name"  to 

hostname_field = "dNSHostName"

https://github.com/joshinryz/ansible_ldap_inventory/commit/05626548f3ae4a08ef61b0e4bf388a861b5791b5
