### ISSUE TITLE
Some General Issues and Questions

### ISSUE THREAD

**Issue by BNCUser** [joshinryz/ansible_ldap_inventory#24]
Hello,

Iam trying to use your ldap inventory script for ansible to generate a dynamic Inventory. But have some issues to get it start. 
If i try to run over CLI, i get this one: (with adhoc.yaml i get the error there is no adhoc.yaml of course)

[root@ansible site-packages]# ansible-inventory -i ldap_inventory.yaml --list
[WARNING]: Unable to parse /usr/lib/python3.6/site-packages/ldap_inventory.yaml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}
[root@ansible site-packages]#

When i try it via Dash and do a job with this inventory-script i get:

ansible-inventory 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /tmp/awx_5739_k_o5anb8/tmpx75ji8ue as it did not pass it's verify_file() method
auto declined parsing /tmp/awx_5739_k_o5anb8/tmpx75ji8ue as it did not pass it's verify_file() method
toml declined parsing /tmp/awx_5739_k_o5anb8/tmpx75ji8ue as it did not pass it's verify_file() method
 [WARNING]:  * Failed to parse /tmp/awx_5739_k_o5anb8/tmpx75ji8ue with script
plugin: Inventory script (/tmp/awx_5739_k_o5anb8/tmpx75ji8ue) had an execution
error: Traceback (most recent call last):   File
"/tmp/awx_5739_k_o5anb8/tmpx75ji8ue", line 191, in <module>     raise
AnsibleError(msg) ansible.errors.AnsibleError: Failed to import the required
Python library (python-ldap) on awx's Python
/var/lib/awx/venv/ansible/bin/python. See https://pypi.org/project/python-ldap/
for more info. Please read module documentation and install in the appropriate
location. Import Error: Traceback (most recent call last):   File
"/tmp/awx_5739_k_o5anb8/tmpx75ji8ue", line 172, in <module>     import ldap
ModuleNotFoundError: No module named 'ldap'

i took over the ansible project from an old employee, but iam totally new to Ansible and docker. Maybe you can help me a little?

**Comment by joshinryz** [comment]
Hello, can you run in debug mode for your ansible inventory? That may help on the output. Also, are you using kerberos? If so make sure you can klist your credentials. 

As for the docker, looks like your image is lacking dependencies to run it per the output.

**Comment by BNCUser** [comment]
Hello, first, thank you for answering me :) thats the hole output though the Dashboard with Verbosity on Debug. You mean that right? yes we are useing kerberos, but i struggle to add the credentials though the Webinterface. When i start tough CLI, i have the following script:

YAML file:
"
---
plugin: ldap_inventory
domain: "ldap://xxx-server.bnc.local:636"
username: "xxx@xxx.local"
password: "xxx"
search_ou: "CN=Computers,DC=bnc,DC=local"
"
i trigger it with the example command what you write in Readme.

Debug Output:

  2.675 INFO     Updating inventory 2: BNC
    3.208 DEBUG    Using base command: python /usr/bin/ansible-inventory -i /tmp/awx_5759_dc_h2c5i/tmplkyamseg --playbook-dir /tmp/awx_5759_dc_h2c5i -vvvvv
    3.208 INFO     Reading Ansible inventory source: /tmp/awx_5759_dc_h2c5i/tmplkyamseg
    3.212 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    3.212 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    3.212 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1157, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1047, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 215, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 198, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /tmp/awx_5759_dc_h2c5i/tmplkyamseg as it did not pass it's verify_file() method
auto declined parsing /tmp/awx_5759_dc_h2c5i/tmplkyamseg as it did not pass it's verify_file() method
toml declined parsing /tmp/awx_5759_dc_h2c5i/tmplkyamseg as it did not pass it's verify_file() method
 [WARNING]:  * Failed to parse /tmp/awx_5759_dc_h2c5i/tmplkyamseg with script
plugin: Inventory script (/tmp/awx_5759_dc_h2c5i/tmplkyamseg) had an execution
error: Traceback (most recent call last):   File
"/tmp/awx_5759_dc_h2c5i/tmplkyamseg", line 191, in <module>     raise
AnsibleError(msg) ansible.errors.AnsibleError: Failed to import the required
Python library (python-ldap) on awx's Python
/var/lib/awx/venv/ansible/bin/python. See https://pypi.org/project/python-ldap/
for more info. Please read module documentation and install in the appropriate
location. Import Error: Traceback (most recent call last):   File
"/tmp/awx_5759_dc_h2c5i/tmplkyamseg", line 172, in <module>     import ldap
ModuleNotFoundError: No module named 'ldap'
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 268, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/script.py", line 161, in parse
    raise AnsibleParserError(to_native(e))
 [WARNING]:  * Failed to parse /tmp/awx_5759_dc_h2c5i/tmplkyamseg with yaml
plugin: Syntax Error while loading YAML.   mapping values are not allowed in
this context  The error appears to be in '/tmp/awx_5759_dc_h2c5i/tmplkyamseg':
line 9, column 10, but may be elsewhere in the file depending on the exact
syntax problem.  The offending line appears to be:  DOCUMENTATION = '''
name: ldap_inventory          ^ here
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 268, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/yaml.py", line 105, in parse
    raise AnsibleParserError(e)
 [WARNING]:  * Failed to parse /tmp/awx_5759_dc_h2c5i/tmplkyamseg with ini
plugin: /tmp/awx_5759_dc_h2c5i/tmplkyamseg:5: Expected key=value host variable
assignment, got: __future__
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 268, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/ini.py", line 138, in parse
    raise AnsibleParserError(e)
 [WARNING]: Unable to parse /tmp/awx_5759_dc_h2c5i/tmplkyamseg as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.

**Comment by joshinryz** [comment]
It may be a little difficult to troubleshoot your setup, but to start - there is some dependencies missing and its likely you dont have a kerberos token. Can you reach out to me over email and we can troubleshoot there? github doesnt really provide a great platform for back/forth troubleshooting. josh(dot)robinett(at)gmail.com(dot)com
