### ISSUE TITLE
Things broke after specific commit

### ISSUE THREAD

**Issue by icanhazpython** [joshinryz/ansible_ldap_inventory#25]
After commit 9abc9d989de0bf752e2146257e401596da593ad6 was introduced, I am experiencing these issues:

- Missing some hosts
- OU group names have changed. For example, "application_hosts" is now "application"

**Comment by joshinryz** [comment]
Morning,

Thats odd - let me test and see if I can get the same result.

**Comment by joshinryz** [comment]
Ok, I cant reproduce it - and I have a lot of groups that get their name changed. Can you get me the ldap_inventory.yml settings you are using so I can test the same options? (make sure to hygiene any sensitive details)

**Comment by icanhazpython** [comment]
Sure thing:
```
plugin: ldap_inventory
domain: 'ldap://1.2.3.4:389'
username: ansible@MYDOMAIN.COM
password: "xxxxxxxxxxxx"
search_ou: "DC=mydomain,DC=com"
online_only: false
fqdn_format: true
```

I tested about 10 different commits and found that the issue presents at/after the one mentioned above.
Thanks

**Comment by joshinryz** [comment]
Think i might have found the issue. Working on a fix
