### ISSUE TITLE
OU with spaces or minus sign are trimmed. Some hosts not discovered

### ISSUE THREAD

**Issue by PabReg** [joshinryz/ansible_ldap_inventory#26]
` foundOUs = re.findall('(?u)OU=(\w{1,})',ouString)`

Current regex does not involve spaces or other symbols

![image](https://user-images.githubusercontent.com/59601475/167127557-03791173-5af6-4035-8b74-a50c316d434e.png)

I would think of something like this regex:

`OU=.*?[^\\,],`

![image](https://user-images.githubusercontent.com/59601475/167128097-63b327af-0f8b-4f36-8931-ad2b715592c7.png)

It would cache even nasty names like these:
![image](https://user-images.githubusercontent.com/59601475/167128175-7694d105-b1fb-4983-9cf6-9552df0d9a59.png)

-----------------------------------------------

Another strange behavior
There are two servers with names: "rde" and "rde-srv2019"
rde is being found and added and rde-srv2019 is not. Why could it be? Where are no special symbols in name
both server has objectclass=computer

**Comment by PabReg** [comment]
Another thing:

I have OU=servers
And inside that OU there are two more OU=Windows and OU=Other

OU=windows contains contains 18 computers

if exclude_groups if used:

`exclude_groups: "servers_other"`
or
`exclude_groups: "other"`

the result is that group: servers_windows contains only 1 host

**Comment by joshinryz** [comment]
Morning PabReg,

On the first question another user noticed this and made a post. I made a fix which I've been testing this week.

We should have it patched shortly. 

Whats your inventory config? There isnt anything specific that would exclude hosts minus the exclude_groups or account age.

**Comment by PabReg** [comment]
`---
plugin: ldap_inventory
domain: 'ldap://dc1.local.com'
username: r*****P
password: "G*********M"
search_ou: "DC=local,DC=com"
exclude_groups: "other"`

**Comment by joshinryz** [comment]
Let me get a new version pushed this weekend and you can test your mileage.
