### ISSUE TITLE
Trouble Getting Inventory Plugin to Work

### ISSUE THREAD

**Issue by robbie2121** [joshinryz/ansible_ldap_inventory#27]
Hello,

I'm new to ansible and linux. I was wondering if you could help me out in setting up your inventory plugin.

Im running Ubuntu 22.04 with latest ansible.

I'm a little confused what base directory and base folder are referring too.

**1) Currently my ansible structure is like this:**
![image](https://user-images.githubusercontent.com/47472623/167199262-64e8c3e3-dd8b-4b58-b2bc-386e9343e6c1.png)

**2) I've put my ldap_inventory.yaml file at:**
 ./etc/ansible which I think is right (as this can go anywhere i believe as long as path is specified in the command). But where exactly do I put the ldap_inventory.py file? Currently, I created a plugins/inventory folder at ./etc/ansible and copied the ldap_inventory.py file there

**3) Every time I run command: ansible-inventory -i ldap_inventory --list , I get error:**
![image](https://user-images.githubusercontent.com/47472623/167200872-4d98a97e-90b7-46ce-8c87-82673cc4e607.png)

**4) this is what my ldap_inventory.yaml file settings look like:**
![image](https://user-images.githubusercontent.com/47472623/167200752-c228e14d-1a53-4167-9595-37391f2edf9c.png)

Thank you

**Comment by joshinryz** [comment]
Hey Robbie!  Glad you are getting into Ansible. I would likely avoid using the /etc folders for most cases.
You should setup a project in your source code versioning software, prolly in your home folder.

However, a good primer for all of this is Ansible itself, they have a good document on creating folder structure.

https://docs.ansible.com/ansible/2.8/user_guide/playbooks_best_practices.html#directory-layout

I'll leave this open for now, and feel free to follow-up once you've got the folder structure down.

**Comment by robbie2121** [comment]
Thanks! Ill take a look at the link and follow-up soon!

**Comment by robbie2121** [comment]
> Hey Robbie! Glad you are getting into Ansible. I would likely avoid using the /etc folders for most cases. You should setup a project in your source code versioning software, prolly in your home folder.
> 
> However, a good primer for all of this is Ansible itself, they have a good document on creating folder structure.
> 
> https://docs.ansible.com/ansible/2.8/user_guide/playbooks_best_practices.html#directory-layout
> 
> I'll leave this open for now, and feel free to follow-up once you've got the folder structure down.

Hi Joshinryz! This is what my folder structure looks like now:
![image](https://user-images.githubusercontent.com/47472623/167219195-6c1523b6-7880-45d9-a2a3-af928082a54c.png)

I then placed the ldap_inventory.py file into:
![image](https://user-images.githubusercontent.com/47472623/167219254-cdacea8e-7e2c-495c-9c38-22910f556248.png)

This is the output I receive after running the command: ansible-inventory -i ldap_inventory --list:
![image](https://user-images.githubusercontent.com/47472623/167219360-273291da-9030-4fd9-8025-b7362686b415.png)

Thank you

**Comment by joshinryz** [comment]
Can you run `ansible --version` and grab the output (filtering out anything sensitive)

**Comment by robbie2121** [comment]
Yes sir!

![image](https://user-images.githubusercontent.com/47472623/167223251-7df9c140-8034-416d-bc1a-514cc8fc2d2f.png)

**Comment by joshinryz** [comment]
ok, I think you likely should add a plugin path to your config, or add the plugin to the already used paths.

**Comment by robbie2121** [comment]
ohh I just noticed that. I will try and let you know what happens!

**Comment by joshinryz** [comment]
Also for review as well : https://docs.ansible.com/ansible/latest/reference_appendices/config.html

**Comment by robbie2121** [comment]
> ok, I think you likely should add a plugin path to your config, or add the plugin to the already used paths.

I copied the ldap_inventory.py file to all the following locations (and all returned the same error as before):

/home/ansible_admin/.ansible/plugins/modules
/usr/share/ansible/plugins/modules
/usr/lib/python3/dist-packages/ansible
/home/ansible_admin/.ansible/collections
/usr/share/ansible/collections

I then copied the ldap_inventory.py file to /usr/bin/ansible and now receive error:
![image](https://user-images.githubusercontent.com/47472623/167226168-b3d9b873-2daf-4a8a-9e42-1dd26bbd2771.png)

**Comment by robbie2121** [comment]
I think i used the wrong path in the ansible.cfg... playing around with it currently..

**Comment by joshinryz** [comment]
Yup, its an inventory plugin, check the config option here:
https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-inventory-plugin-path

**Comment by robbie2121** [comment]
I'm still having problem figuring it out :(

**This is what i've done:**
1) copied the file ldap_inventory.py to /usr/share/ansible/plugins/inventory/
2) Copied the file ldap_inventory.yaml to /usr/share/ansible/plugins/inventory/
3) in ansible.cfg, i tried using:
inventory_plugins=./plugins/inventory and the default inventory_plugins=~/.ansible/plugins/inventory:/usr/share/ansible/plugins/inventory


**This is the error i'm getting from command "ansible-inventory -i /usr/share/ansible/plugins/inventory/ldap_inventory.yaml --list ANSIBLE_DEBUG=1 -vvv ":**

ansible-inventory -i /usr/share/ansible/plugins/inventory/ldap_inventory.yaml --list ANSIBLE_DEBUG=1 -vvv
ansible-inventory [core 2.12.4]
  config file = /home/ansible_admin/ansible.cfg
  configured module search path = ['/home/ansible_admin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/ansible_admin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-inventory
  python version = 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
Using /home/ansible_admin/ansible.cfg as config file
host_list declined parsing /usr/share/ansible/plugins/inventory/ldap_inventory.yaml as it did not pass its verify_file() method
script declined parsing /usr/share/ansible/plugins/inventory/ldap_inventory.yaml as it did not pass its verify_file() method
toml declined parsing /usr/share/ansible/plugins/inventory/ldap_inventory.yaml as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /usr/share/ansible/plugins/inventory/ldap_inventory.yaml with auto
plugin: inventory config '/usr/share/ansible/plugins/inventory/ldap_inventory.yaml' specifies unknown
plugin 'ldap_inventory'
  File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3/dist-packages/ansible/plugins/inventory/auto.py", line 53, in parse
    raise AnsibleParserError("inventory config '{0}' specifies unknown plugin '{1}'".format(path, plugin_name))
[WARNING]:  * Failed to parse /usr/share/ansible/plugins/inventory/ldap_inventory.yaml with yaml
plugin: Plugin configuration YAML file, not YAML inventory
  File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3/dist-packages/ansible/plugins/inventory/yaml.py", line 112, in parse
    raise AnsibleParserError('Plugin configuration YAML file, not YAML inventory')
[WARNING]:  * Failed to parse /usr/share/ansible/plugins/inventory/ldap_inventory.yaml with ini plugin:
Invalid host pattern '---' supplied, '---' is normally a sign this is a YAML file.
  File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3/dist-packages/ansible/plugins/inventory/ini.py", line 136, in parse
    raise AnsibleParserError(e)
[WARNING]: Unable to parse /usr/share/ansible/plugins/inventory/ldap_inventory.yaml as an inventory
source
[WARNING]: No inventory was parsed, only implicit localhost is available
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}

Any more suggestion is GREATLY appreciated!!!


**This is the active directory path/ou I am searching:**

![image](https://user-images.githubusercontent.com/47472623/167239990-49d08b7e-d6e4-4a43-9cdc-2b4ee89014f7.png)


**this is my ldap_inventory.yaml file:**

---
plugin: ldap_inventory
domain: 'ldaps://domain_controller_hostname:636'
username: domain_admin@xxxxxxx.com
password: "xxxxxxxxxxx"
search_ou: "OU=DCs,DC=xxxxxxx,DC=com"

Thank you

**Comment by robbie2121** [comment]
Thank you joshinryz! Im still working on it and will report back!

**Comment by robbie2121** [comment]
if im using python3 and install using command:
pip3 install python3-ldap is that compatible with the plugin (instead of using pip install python-ldap)?

just trying to eliminate causes!

**Comment by robbie2121** [comment]
Hi Joshinryz,

Ive gotten past this step now! I just need to figure out where and how to import the windows certificate(s) for LDAPS into ubuntu ca store now.

I will close the ticket now. Thank you for your help!!
