### ISSUE TITLE
Some hosts are missing. Using exlude_groups drasticaly decreases hosts found

### ISSUE THREAD

**Issue by PabReg** [joshinryz/ansible_ldap_inventory#29]
After last update spaces and minus signs are read correctly in OUs but not all hosts are found. Host names do not contain any special symbols or common language specific letters
For example:
![image](https://user-images.githubusercontent.com/59601475/167557228-6c58532b-3fe5-4f8c-9f08-cb233df29fc7.png)

If `exclude_groups: "other"` is used then the result contains only one host in windows group
![image](https://user-images.githubusercontent.com/59601475/167557525-745d9ae8-540c-4855-b1ea-0ba75dbfa2ea.png)

**Comment by joshinryz** [comment]
Can you run -vvv and set your environment variable `ANSIBLE_DEBUG=True`. Look to see if it notes why they are excluded or removed.

**Comment by PabReg** [comment]
`ansible-inventory -i ldap_inventory.yaml -e ANSIBLE_DEBUG=True --list -vvv
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]. This
 feature will be removed from ansible-core in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
/usr/local/lib/python3.6/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.exceptions import InvalidSignature
ansible-inventory [core 2.11.11]
  config file = /playbooks/ESET-agent/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.3
  libyaml = True
Using /playbooks/ESET-agent/ansible.cfg as config file
host_list declined parsing /playbooks/ESET-agent/ldap_inventory.yaml as it did not pass its verify_file() method
script declined parsing /playbooks/ESET-agent/ldap_inventory.yaml as it did not pass its verify_file() method
toml declined parsing /playbooks/ESET-agent/ldap_inventory.yaml as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /playbooks/ESET-agent/ldap_inventory.yaml with auto plugin: name 'sub' is not defined
  File "/usr/local/lib/python3.6/site-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/inventory/auto.py", line 58, in parse
    plugin.parse(inventory, loader, path, cache=cache)
  File "/playbooks/ESET-agent/plugins/inventory/ldap_inventory.py", line 484, in parse
    display.debug("DEBUG: Skipping %s as group %s was found in ldap_exclude_groups" % (hostName, sub))
[WARNING]:  * Failed to parse /playbooks/ESET-agent/ldap_inventory.yaml with yaml plugin: Plugin configuration YAML file, not YAML inventory
  File "/usr/local/lib/python3.6/site-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/inventory/yaml.py", line 112, in parse
    raise AnsibleParserError('Plugin configuration YAML file, not YAML inventory')
[WARNING]:  * Failed to parse /playbooks/ESET-agent/ldap_inventory.yaml with ini plugin: Invalid host pattern '---' supplied, '---' is normally a sign this is a YAML file.
  File "/usr/local/lib/python3.6/site-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/inventory/ini.py", line 136, in parse
    raise AnsibleParserError(e)
[WARNING]: Unable to parse /playbooks/ESET-agent/ldap_inventory.yaml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
`

ldap_inventory.yaml
`---
plugin: ldap_inventory
domain: 'ldap://spinta2.limedika.lt'
username: readLDAP
password: "G5'H-xqzZeP$HW>M"
search_ou: "DC=limedika,DC=lt"
exclude_groups: "other"
`

**Comment by joshinryz** [comment]
```
File "/playbooks/ESET-agent/plugins/inventory/ldap_inventory.py", line 484, in parse
display.debug("DEBUG: Skipping %s as group %s was found in ldap_exclude_groups" % (hostName, sub))
```
Ok, i think this is crashing because you are excluding a group that does not exist. We likely need to defend users from themselves in this case. But if the the group name you used isn't an OU or you arent getting it from memberOf parsing, this will fail and terminate early. 

I'll see if we can add some protection logic for invalid excludes.

**Comment by PabReg** [comment]
Yes you are right. I made a mistake and instead of "Other" I typed "other" and because of case sensitivity it's not found.
After changing it everything works as expcted.

Still missing some hosts comparing inventory and LDAP.
Even tried a new fresh install on Ubuntu instead of Centos result is the same

Any way to debug that?

**Comment by joshinryz** [comment]
I would imagine something is crashing early, can you do the debug output again (make sure ANSIBLE_DEBUG=True on your terminal) and see where it stops the process ?

**Comment by joshinryz** [comment]
Just a note, PabReg, since I dont see the debug output above. Can you add the variable in front of your comamnd.
`ANSIBLE_DEBUG=True ansible -i .......` for example

**Comment by PabReg** [comment]
I ran with ANSIBLE_DEBU=True and it gave me a lot of messages.
I'm providing everything at the beggining:

 28484 1652333225.62130: starting run
ansible-inventory 2.10.8
  config file = /playbooks/ESET-agent/ansible.cfg
  configured module search path = ['/home/regimantas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
Using /playbooks/ESET-agent/ansible.cfg as config file
 28484 1652333225.79016: Added group all to inventory
 28484 1652333225.79018: Added group ungrouped to inventory
 28484 1652333225.79021: Group all now contains ungrouped
 28484 1652333225.79024: Examining possible inventory source: /playbooks/ESET-agent/ldap_inventory.yaml
 28484 1652333225.79132: trying /usr/lib/python3/dist-packages/ansible/plugins/cache
 28484 1652333225.79167: Loading CacheModule 'memory' from /usr/lib/python3/dist-packages/ansible/plugins/cache/memory.py
 28484 1652333225.79180: trying /playbooks/ESET-agent/plugins/inventory/__pycache__
 28484 1652333225.79185: trying /playbooks/ESET-agent/plugins/inventory
 28484 1652333225.79189: trying /usr/lib/python3/dist-packages/ansible/plugins/inventory
 28484 1652333225.79222: Loading InventoryModule 'host_list' from /usr/lib/python3/dist-packages/ansible/plugins/inventory/host_list.py (searched paths: /usr/lib/python3/dist-packages/ansible/plugins/inventory:/playbooks/ESET-agent/plugins/inventory:/playbooks/ESET-agent/plugins/inventory/__pycache__)
 28484 1652333225.79278: Loaded config def from plugin (inventory/script)
 28484 1652333225.79281: Loading InventoryModule 'script' from /usr/lib/python3/dist-packages/ansible/plugins/inventory/script.py (searched paths: /usr/lib/python3/dist-packages/ansible/plugins/inventory:/playbooks/ESET-agent/plugins/inventory:/playbooks/ESET-agent/plugins/inventory/__pycache__)
 28484 1652333225.79308: Loading InventoryModule 'auto' from /usr/lib/python3/dist-packages/ansible/plugins/inventory/auto.py (searched paths: /usr/lib/python3/dist-packages/ansible/plugins/inventory:/playbooks/ESET-agent/plugins/inventory:/playbooks/ESET-agent/plugins/inventory/__pycache__)
 28484 1652333225.79351: Loaded config def from plugin (inventory/yaml)
 28484 1652333225.79354: Loading InventoryModule 'yaml' from /usr/lib/python3/dist-packages/ansible/plugins/inventory/yaml.py (searched paths: /usr/lib/python3/dist-packages/ansible/plugins/inventory:/playbooks/ESET-agent/plugins/inventory:/playbooks/ESET-agent/plugins/inventory/__pycache__)
 28484 1652333225.79405: Loading InventoryModule 'ini' from /usr/lib/python3/dist-packages/ansible/plugins/inventory/ini.py (searched paths: /usr/lib/python3/dist-packages/ansible/plugins/inventory:/playbooks/ESET-agent/plugins/inventory:/playbooks/ESET-agent/plugins/inventory/__pycache__)
 28484 1652333225.79624: Loading InventoryModule 'toml' from /usr/lib/python3/dist-packages/ansible/plugins/inventory/toml.py (searched paths: /usr/lib/python3/dist-packages/ansible/plugins/inventory:/playbooks/ESET-agent/plugins/inventory:/playbooks/ESET-agent/plugins/inventory/__pycache__)
 28484 1652333225.79627: Attempting to use plugin host_list (/usr/lib/python3/dist-packages/ansible/plugins/inventory/host_list.py)
host_list declined parsing /playbooks/ESET-agent/ldap_inventory.yaml as it did not pass its verify_file() method
 28484 1652333225.79631: Attempting to use plugin script (/usr/lib/python3/dist-packages/ansible/plugins/inventory/script.py)
script declined parsing /playbooks/ESET-agent/ldap_inventory.yaml as it did not pass its verify_file() method
 28484 1652333225.79636: Attempting to use plugin auto (/usr/lib/python3/dist-packages/ansible/plugins/inventory/auto.py)
 28484 1652333225.79639: Loading data from /playbooks/ESET-agent/ldap_inventory.yaml
 28484 1652333225.83181: Loaded config def from plugin (inventory/ldap_inventory)
 28484 1652333225.83186: Loading InventoryModule 'ldap_inventory' from /playbooks/ESET-agent/plugins/inventory/ldap_inventory.py (searched paths: /usr/lib/python3/dist-packages/ansible/plugins/inventory:/playbooks/ESET-agent/plugins/inventory:/playbooks/ESET-agent/plugins/inventory/__pycache__)
 28484 1652333225.83239: Loading data from /playbooks/ESET-agent/ldap_inventory.yaml
 28484 1652333225.84377: DEBUG: ldap_results Received 457 results in 1 pages.


Later there are mostly processing commands.

I'm finding 3 anomalies:
1. DEBUG: ldap_results Received 457 results in 1 pages. I'm only seeing 454 computers in Active Directory. Does it counts anything alse despite Computers ?
2. Debug log don't have anything containing missing hosts. No errors/warnings or other messages
3. Narrowing search_ou from "DC=local,DC=com" to "OU=windows,OU=servers,DC=local,DC=com" provides correct results and I'm seeing all 18 hosts

Any thoughts?

**Comment by joshinryz** [comment]
Hey Pabreg, usually it doesnt let you point to the root DN. This is more of a limitation of the python-ldap module binding than the plugin. Id testing pointing to OUs and see if you get a difference.  If you have multiple top level OUs you can handle that in a different way.

**Comment by PabReg** [comment]
What's the best way to handle multiple top level OUs?

**Comment by joshinryz** [comment]
Hey Sorry to leave you hanging, its bee a bust month. Ok, so they best way is to create multiple inventory yaml files in a single directory like ./inventory/first_ldap_inventory.yaml & ./inventory/second_ldap_inventory.yaml

When you target, use ansible-playbook -i ./inventory/ 


It will include dynamic and static files into a single inventory.
