### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by zhouxin8571** [joshinryz/ansible_ldap_inventory#3]
[WARNING]: Unable to parse /etc/ansible/ldap_inventory as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

**Comment by joshinryz** [comment]
Can you run in verbose mode and supply the full output. Thanks

**Comment by joshinryz** [comment]
Closing - please feel free to re-open when you have more details. Thanks.
