### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by watsonb** [joshinryz/ansible_ldap_inventory#31]
In the Configuration Example section of the README, the environment variables specified:

```
LDAP_USERNAME, LDAP_PASSWORD and SEARCH_OU
```

are incorrect.  The actual environment variable names (in the code) are:

```
LDAP_USER, LDAP_PASS and SEARCH_OU
```

**Comment by joshinryz** [comment]
https://github.com/joshinryz/ansible_ldap_inventory/pull/30

**Comment by watsonb** [comment]
Thanks!
