### ISSUE TITLE
Problem to get plugin running with FreeIPA LDAP

### ISSUE THREAD

**Issue by e36Alex** [joshinryz/ansible_ldap_inventory#34]
Hello,

this is the first time, i try to use ansibles dynamic inventory.
I would like to connect the plugin to freeipa's LDAP.

This is the actual output i get:
`root@ansible:~# ansible-inventory -i /etc/ansible/ldap_inventory.yaml --list -vvv
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]. This
 feature will be removed from ansible-core in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ansible-inventory [core 2.11.12] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
  jinja version = 3.1.2
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/ldap_inventory.yaml as it did not pass its verify_file() method
script declined parsing /etc/ansible/ldap_inventory.yaml as it did not pass its verify_file() method
Parsed /etc/ansible/ldap_inventory.yaml inventory source with auto plugin
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}`

/etc/ansible/ldap_inventory.yaml:
`---
plugin: ldap_inventory
domain: "ds01.home.domain.de"
username: "uid=ansible,cn=users,cn=accounts,dc=home,dc=domain,dc=de"
password: "secret"
search_ou: "cn=computers,cn=accounts,dc=home,dc=domain,dc=de"
group_membership: True
auth_type: simple`

The .py i placed at:
/etc/ansible/plugins/inventory/ldap_inventory.py

Would be great, if someone could help me to get this running.

Thanks, Alex

**Comment by e36Alex** [comment]
Tried playing around with ldapsearch and maybe i got an idea:
when i search for this, no host is shown:
`cn=host.home.domain.de,cn=computers,cn=accounts,dc=home,dc=domain,dc=de`

when i search for this, the host is shown:
`fqdn=host.home.domain.de,cn=computers,cn=accounts,dc=home,dc=domain,dc=de`

I tried to replace all "cn" with "fqdn" in the ldap_inventory.py, but this does not make a change.

But maybe this information can help.

**Comment by mwtrigg** [comment]
I believe your issue is caused by the fact that your computer object is not in an OU.  This inventory plugin was written with the intent that computer objects would always be found within OUs.

I do not hav an instance of FreeIPA available to test against.

**Comment by mwtrigg** [comment]
See Issue #33
