### ISSUE TITLE
Getting it to work in Tower?

### ISSUE THREAD

**Issue by kobaltfox** [joshinryz/ansible_ldap_inventory#4]
I got it working great from Ansible CLI great, thanks! However, I am trying to get it running for Ansible Tower. Have you done this? It always fails. I have an **Inventory** created with a **custom script** as the source. I tried putting the variables in as 'environmental variables':

plugin: adhosts
domain: 'ldap://dc.company.com'
auth_type: simple
username: username
password: "supersecret"
search_ou: "OU=Computers,DC=company,DC=com"
fqdn_format: true

But is always fails to sync. It's not returning any parsable data. Either it isn't getting the above vars, or something else is wrong with my methodology?

Possibly not setup to pass variables like here using the yaml file for OU and credentials? If you (or anyone) has done this same stuff by in Tower, would love to touch base!

**Comment by joshinryz** [comment]
Hey Kobaltfox,

Yes we use this with tower. Here is our setup:

We create a yaml file with the configuration we need inside a vaulted file. (since vaulted strings arent supported yet) [ansible-vault create ....]

The file is in the root of our source code project. 

Here is a screenshot of the setup:
![image](https://user-images.githubusercontent.com/29162798/70175476-68f7c900-169c-11ea-9d63-a8df5b3e13bf.png)

Notice we have to supply an explicit vault file (since source code repositories dont support vault passwords under inventories in tower - dont worry i told them already)

**Comment by joshinryz** [comment]
Oh - also, i am assuming you renamed the plugin or just filled in an example since 'adplugin' isnt its name?

**Comment by kobaltfox** [comment]
> Oh - also, i am assuming you renamed the plugin or just filled in an example since 'adplugin' isnt its name?

yes. I renamed it. But it was a minor change for our environment conventions.

**Comment by kobaltfox** [comment]
Hey thanks Joshinryz, 
So I am currently using a manual project, instead of a Git. Mainly as I figure this all out, then our group will implement project management with Git. 
So I have adhosts.yaml in the project directory. I try to save my new inventory host, and I get the following error:
![inventory_error](https://user-images.githubusercontent.com/37553370/70179302-74022780-16a3-11ea-820a-52948af820ac.PNG)

**Comment by kobaltfox** [comment]
Here's the methodology I am following. Perhaps I'm just flawed in mu approach:

A) I've got a project for the overall operations I am taking on a series of hosts. This creates the directory for my files. And a place to associate my **Job Templates**. This is a **MANUAL** project.
B) I have **Job Template** which uses my **invenADHosts** Inventory, the aforementioned project, and a **.yml playbook** that is my project directory.
C) In the **invenADHosts** inventory, I have nothing in groups and hosts. I only have one item in 'SOURCES' called **adhosts**, which is a custom script as a source. This is setup with no environmental variables, and references the **python script** you wrote for pulling inventory from AD.
D) The script has only one change, I call the plugin 'adhosts'. 

And now I am experimenting with where to put the variables that get passed to the python script. I've tried 
1) the variables in the **invenADHosts** settings 
![inventory_error1](https://user-images.githubusercontent.com/37553370/70180863-73b75b80-16a6-11ea-9ba9-aa30daf89def.PNG)

or 2) the environmental variables in the **adhosts** settings.
![inventory_error2](https://user-images.githubusercontent.com/37553370/70180886-7c0f9680-16a6-11ea-92fc-d28dcf852320.PNG)

I hope that clarifies. Thanks for any thoughts!!

**Comment by joshinryz** [comment]
So each dynamic inventory file has a function called verify_file()
In your example, it looks like tower is creating a temp file with your settings and trying to call it.

This wont work, as the file name has to end with whatever verify_file() expects.

**host_list declined parsing /tmp/awx_332_17q818n1/tmp9h1a7d7t as it did not pass it's verify_file() method**

Honestly - this isnt the first ive see this, check similiar problems here:
https://github.com/ansible/awx/issues/4154

Im not sure there is a work around for tower - other than using a source code repository.

**Comment by joshinryz** [comment]
Btw - the inventory can be a completely separate from your templates etc project wise.
Tower basically stores the inventory - which can then be called by and project/template/workflow/job

**Comment by joshinryz** [comment]
Let me know if you got this working . Otherwise I'll close this out next week. Thanks

**Comment by joshinryz** [comment]
Closing , feel free to comment if I can help anymore
