### ISSUE TITLE
Guide on using with AWX/Tower

### ISSUE THREAD

**Issue by stuartluscombe** [joshinryz/ansible_ldap_inventory#9]
I'm quite new to using AWX and have come across your plugin as we're wanting to import hosts from AD. 

I understand the basics of how your plugin should work and have read through a previous issue raised, but I can't quite get my head around how to get the plugin in to AWX considering it's running as a set of Docker containers and I want it to persist.

Would it be possible for you to please put together a few steps on how to get started?

**Comment by joshinryz** [comment]
Hey, 

No there is no guide specific to AWX. However, there are a few things you will need to resolve . 

First, you need to get the python dependency installed for AWX task docker image.

Second, the plugin should be in your source code repository - i would not recommend copying your files into awx, you should create a project and source the inventory from there. (the same as tower).

Most of the above can be resolved by setting up your own virtualenv for AWX. There are guides for that, that are outside the scope of this project. But the idea is you setup a virtualenv on your local host, then when building AWX it copies that virualenv.

Other methods are attaching to the terminal after you install / upgrade and change what you need or cloning AWX and customizing your own Docker Run files / build scripts.

Anyhow, when you get things running - if you hit issues let me know.

**Comment by joshinryz** [comment]
Closed since this is outside the scope of this project.
